 /*
 COMP9024 Exercise Q5.1

 collatzeFib.c -Write a C-function that takes a positive integer n as argument and prints a series of numbers generated by the following algorithm, until 1 is reached:

 if n is even, then n ? n/2
 
 if n is odd, then n ? 3*n+1

 Author: Jatin Gupta (z5240221@unsw.edu.au)

 Date- 10-June-19
    
 */
 
 #include<stdio.h>
 #include<stdlib.h>
 
 
 void generate(int n) {
 	while(n != 1) {
 		if (n % 2 == 0) {
 			n = n/2;
 		} else {
 			n = (3 * n) + 1;
 		}
 		printf("%d ", n);
 	}
 }
 
 int main(void) {
 	generate(3);
	
 	return 0;
 }
